# xpaths.py
input_xpath = "//input[@type='search' and contains(@class, 'hz-header__search-bar__input')]"
search_xpath = "//button[@type='submit' and contains(@class, 'hz-header__search-bar__submit hz-header__search-icon icon-font icon-magnifying_glass')]"
product_xpath = "//div[@role='group' and contains(@class, 'hz-product-card__link')]"
name_xpath = ".//span[@class='hz-color-link__text ']"
price_xpath = ".//span[@class='hz-product-price hz-product-price--v2 hz-product-price--final']/span"
link_xpath = ".//a[@class='ProductTitle__StyledLink-f609cb-0 mhyEs hz-product-card__product-title text-l hz-color-link hz-color-link--black hz-color-link--enabled ']"
image_xpath = ".//img"
rating_xpath = "//span[@class='star-rating hz-track-me hz-product-card__review-stars']"
next_page_xpath = "//span[text()='Next Page']"
description_xpath = "//div[@class='vp-redesign-description']"
specification_xpath = "//li[@data-component='Product Specifications']"
product_id_xpath = "//dt[contains(text(), 'Product ID')]/following-sibling::dd"
manufactured_by_xpath = "//dt[contains(text(), 'Manufactured By')]/following-sibling::dd/a"
sold_by_xpath = "//dt[contains(text(), 'Sold By')]/following-sibling::dd"
size_weight_xpath = "//dt[contains(text(), 'Size/Weight')]/following-sibling::dd"
color_xpath = "//dt[contains(text(), 'Color')]/following-sibling::dd"
materials_xpath = "//dt[contains(text(), 'Materials')]/following-sibling::dd"
category_xpath = "//dt[contains(text(), 'Category')]/following-sibling::dd"
style_xpath = "//dt[contains(text(), 'Style')]/following-sibling::dd"
color_variation_xpath = "//div[@data-event-type='Element Viewed' and @data-component='Product Variation']"
   